toktx --genmipmap ktx_files/FlightHelmet_baseColor.ktx FlightHelmet_baseColor.png
toktx --genmipmap ktx_files/FlightHelmet_baseColor1.ktx FlightHelmet_baseColor1.png
toktx --genmipmap ktx_files/FlightHelmet_baseColor2.ktx FlightHelmet_baseColor2.png
toktx --genmipmap ktx_files/FlightHelmet_baseColor3.ktx FlightHelmet_baseColor3.png
toktx --genmipmap ktx_files/FlightHelmet_baseColor4.ktx FlightHelmet_baseColor4.png
toktx --genmipmap ktx_files/FlightHelmet_normal.ktx FlightHelmet_normal.png
toktx --genmipmap ktx_files/FlightHelmet_normal1.ktx FlightHelmet_normal1.png
toktx --genmipmap ktx_files/FlightHelmet_normal2.ktx FlightHelmet_normal2.png
toktx --genmipmap ktx_files/FlightHelmet_normal3.ktx FlightHelmet_normal3.png
toktx --genmipmap ktx_files/FlightHelmet_normal4.ktx FlightHelmet_normal4.png
toktx --genmipmap ktx_files/FlightHelmet_occlusionRoughnessMetallic.ktx FlightHelmet_occlusionRoughnessMetallic.png
toktx --genmipmap ktx_files/FlightHelmet_occlusionRoughnessMetallic1.ktx FlightHelmet_occlusionRoughnessMetallic1.png
toktx --genmipmap ktx_files/FlightHelmet_occlusionRoughnessMetallic2.ktx FlightHelmet_occlusionRoughnessMetallic2.png
toktx --genmipmap ktx_files/FlightHelmet_occlusionRoughnessMetallic3.ktx FlightHelmet_occlusionRoughnessMetallic3.png
toktx --genmipmap ktx_files/FlightHelmet_occlusionRoughnessMetallic4.ktx FlightHelmet_occlusionRoughnessMetallic4.png
pause